### ISSUE TITLE
where did I go wrong?

### ISSUE THREAD

**Issue by amunizp** [adafruit/Adafruit-IoT-Camera-with-EyeFi-Sketch#1]
We have the X2 eye-fi sd card.

When I compile i get this:

Adafruit_EyeFi.pde:74:23: error: variable ‘sleepTab’ must be const in order to be put into read-only section by means of ‘**attribute**((progmem))’
Adafruit_EyeFi.pde: In function ‘void setup()’:
Adafruit_EyeFi.pde:122:6: error: ‘class SDClass’ has no member named ‘enableCRC’

**Comment by q2dg** [comment]
Here (http://www.ladyada.net/make/IoTcamera) it is said: 

If using the latest Eye-Fi “X2” cards, you'll need to enable this one extra line in the sketch (it’s commented out by default)…around line 122:
SD.enableCRC(true);

**Comment by amunizp** [comment]
Thank you.
